Vagrant.configure("2") do |config|

    nodes = {
        'server01.virtualbox.lan' => { :ip => "10.30.30.10", :memory => 1024, :cpus => 1, :box => "centos/7"},
        'server02.virtualbox.lan' => { :ip => "10.30.30.20", :memory => 1024, :cpus => 1, :box => "centos/7"},
    }

    nodes.each do |node_name, node_opts|
        config.vm.define node_name do |node_config|

            if node_opts[:os] == :windows
                node_config.vm.guest = node_opts[:os]
                node_config.vm.communicator = :winrm
            end

            node_config.vm.hostname = "#{node_name}"
            node_config.vm.box = node_opts[:box]

            node_config.vm.network :private_network, ip: node_opts[:ip]
            node_config.vm.synced_folder ".", "/vagrant", disabled: true

            node_config.vm.provider "virtualbox" do |v|
                v.gui = false
                v.memory = node_opts[:memory]
                v.cpus = node_opts[:cpus]
            end

        end
    end
end

